ROUTINE OPNLib.Serialize.constants [TYPE=INC]
#;Uncovered or unknown type
#define tpUKN 0
///Basic Types
#define tpBSC 1
///List of Data types
#define tpLST 2
///Arrays of Data Types
#define tpARR 3
///Reference to an object (no %Stream or %* object)
#define tpOREF 4
///Array of Objects or RelationshipObjects many/children
#define tpARROBJ 5
///List of Objects
#define tpLSTOBJ 6
///Stream objects (%Stream.*)
#define tpSTREAM 7 